#!/usr/bin/env python
#
# calculatedistance_init.py
#
# Calculate distance between Na+ and Cl- ions, for initial states. When
# calculating the progress coordinate for the initial states, we only care
# about the final timepoint; unlike the case of trajectory segments (i.e.,
# those generated by runseg.sh), we do not need to consider the final timepoint
# of the parent trajectory.
import MDAnalysis
import MDAnalysis.analysis.distances

# Load the trajectory.
universe = MDAnalysis.Universe('structure.psf', 'seg.dcd')

# Calculate the distance between the ions for each timepoint of the trajectory
nacl = universe.select_atoms('resname SOD or resname CLA')
for ts in universe.trajectory:
    dist = MDAnalysis.analysis.distances.self_distance_array(nacl.atoms.positions, box=universe.dimensions)[0]
    print("{:.03f}".format(dist))
