# .readthedocs.yml

version: 2

formats: all

build:
  os: ubuntu-lts-latest
  tools:
    python: miniforge3-latest

sphinx:
  configuration: doc/conf.py

conda:
  environment: doc/doc_env.yaml

python:
  install:
  - path: .
    extra_requirements:
      - doc
