# .readthedocs.yml

version: 2

formats: all

build:
  image: latest

sphinx:
  configuration: doc/conf.py

python:
  version: 3.7
  install:
    - method: pip
      path: .
conda:
  environment: doc/doc_env.yaml
