# .readthedocs.yml

version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

sphinx:
  configuration: doc/conf.py

conda:
  environment: doc/doc_env.yaml

python:
  install:
  - path: .
    extra_requirements:
      - doc
