[build-system]
build-backend = 'setuptools.build_meta:__legacy__'
# Minimum requirements for the build system to execute.
# See current numpy pinning in https://github.com/scipy/oldest-supported-numpy
requires = [
    "setuptools >=40.8.0",
    "wheel",
    "Cython >=0.29.16",  # Note: sync with setup.py
    "numpy >=2.0.0, <3",  # Force numpy>=2 during build time so it works on both 1.XX and 2.XX
    "scipy >=0.19.1",
    "versioneer-518"
]
# Uncommenting this requires adding the top level of the repo to sys.path in the setup.py
# so that it can find the vendorized copy of versioneer. I see that other projects don't
# always include this (pandas, numpy, etc), so leaving this off for now
# build-backend = "setuptools.build_meta"


[project]
name = "westpa"
dynamic = ["version"]
license = "MIT"
license-files = ["LICEN[CS]E.*"]
readme = {file = "README.rst", content-type = "text/x-rst"}
keywords = []
requires-python = ">=3.10"
description = 'WESTPA is a package for constructing and running stochastic simulations using the "weighted ensemble" approach of Huber and Kim (1996).'
dependencies = [
  "numpy >= 1.25.0,<3",
  "scipy >= 0.19.1",
  "h5py >= 2.10",
  "mdtraj >= 1.9.5",
  "pyyaml",
  "pyzmq",
  "matplotlib",
  "blessings",
  "ipykernel",
  "tqdm",
  "pandas",
  "tables",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Operating System :: POSIX",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Cython",
]


[project.urls]
Homepage = "https://westpa.github.io"
Repository = "https://github.com/westpa/westpa"
Documentation = "https://github.readthedocs.io"
Issues = "https://github.com/westpa/westpa/issues"


[project.optional-dependencies]
tests = ["pytest", "pytest-cov", "pytest-rerunfailures", "pytest-timeout"]
mpi = ["mpi4py"]
dev = ["westpa[tests]", "pre-commit"]


[project.scripts]
# WESTPA Core
w_fork = "westpa.cli.core.w_fork:entry_point"
w_states = "westpa.cli.core.w_states:entry_point"
w_run = "westpa.cli.core.w_run:entry_point"
w_truncate = "westpa.cli.core.w_truncate:entry_point"
w_init = "westpa.cli.core.w_init:entry_point"
w_succ = "westpa.cli.core.w_succ:entry_point"
# WESTPA Tools
w_direct = "westpa.cli.tools.w_direct:entry_point"
w_dumpsegs = "westpa.cli.tools.w_dumpsegs:entry_point"
w_postanalysis_matrix = "westpa.cli.tools.w_postanalysis_matrix:entry_point"
w_select = "westpa.cli.tools.w_select:entry_point"
w_ntop = "westpa.cli.tools.w_ntop:entry_point"
w_kinavg = "westpa.cli.tools.w_kinavg:entry_point"
w_eddist = "westpa.cli.tools.w_eddist:entry_point"
w_assign = "westpa.cli.tools.w_assign:entry_point"
w_trace = "westpa.cli.tools.w_trace:entry_point"
w_crawl = "westpa.cli.tools.w_crawl:entry_point"
w_kinetics = "westpa.cli.tools.w_kinetics:entry_point"
w_fluxanl = "westpa.cli.tools.w_fluxanl:entry_point"
w_reweight = "westpa.cli.tools.w_reweight:entry_point"
w_pdist = "westpa.cli.tools.w_pdist:entry_point"
w_ipa = "westpa.cli.tools.w_ipa:entry_point"
w_bins = "westpa.cli.tools.w_bins:entry_point"
w_stateprobs = "westpa.cli.tools.w_stateprobs:entry_point"
w_postanalysis_reweight = "westpa.cli.tools.w_postanalysis_reweight:entry_point"
ploterr = "westpa.cli.tools.ploterr:entry_point"
plothist = "westpa.cli.tools.plothist:entry_point"
w_multi_west = "westpa.cli.tools.w_multi_west:entry_point"
w_red = "westpa.cli.tools.w_red:entry_point"
w_timings = "westpa.cli.tools.w_timings:entry_point"


[tool.setuptools]
zip-safe = false


[tool.setuptools.packages.find]
where = ["src"]


[tool.black]
line-length = 132
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
    /(
        asv_bench/env
      | \.egg
      | \.git
      | \.hg
      | \.mypy_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | docs
      | doc
     )/ | (
      setup.py
      | versioneer.py
      | _version.py
     )
)
'''

# See the docstring in versioneer.py for instructions. Note that you must
# re-run 'versioneer.py setup' after changing this section, and commit the
# resulting files.

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/westpa/_version.py"
versionfile_build = "westpa/_version.py"
tag_prefix = "v"
parentdir_prefix = "westpa-"

