name: Mirror develop to westpa2

on:
  schedule:
    # Once a month on the 28th day at 4 pm UTC, which is ~11 am EST.
    - cron: "00 16 28 * *"
  workflow_dispatch:
    branches:
      - 'westpa2'

jobs:
  mirror-develop-to-westpa2:
    runs-on: ubuntu-latest
    name: Mirror develop branch to westpa2 branch
    if: github.repository_owner == 'westpa'
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.BRANCH_MIRROR_APPID }}
          private-key: ${{ secrets.BRANCH_MIRROR_SECRET }}
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: mirroring step
        run: |
          git checkout westpa2
          git pull --ff-only origin develop
          git push origin westpa2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
